sources:
  - name: raw
    meta:
      external_location: "{{ env_var('DWH_DATA') }}/Financial_dataset/{name}.csv"
    tables:
      - name: financial_dataset
        columns:
          - name: Segment
          - name: Country
          - name: Product
          - name: Discount Band
          - name: Units Sold
          - name: Manufacturing Price
          - name: Sale Price
          - name: Gross Sales
          - name: Discounts
          - name: Sales
          - name: COGS
          - name: Profit
          - name: Date
          - name: Month Number
          - name: Month Name
          - name: Year
      