name: Push Docker Image

on:
  workflow_dispatch:
    
  push:
    branches:
      - main
    paths:
    - 'docker/**'

jobs:

  push:
    runs-on: ubuntu-latest
    env:
      docker-directory: ${{ github.workspace }}/docker
    steps:
      - uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.BROCOLI_DOCKER_USERNAME }}
          password: ${{ secrets.BROCOLI_DOCKER_TOKEN }}

      - name: Build image
        working-directory: ${{ env.docker-directory }}
        run: docker compose build

      - name: Push image to Docker Hub Container Registry
        working-directory: ${{ env.docker-directory }}
        run: docker compose push