name: Push Docker Image

on:
  workflow_dispatch:
    
  push:
    branches:
      - main
    paths:
    - 'Dockerfile'

jobs:

  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.BROCOLI_DOCKER_USERNAME }}
          password: ${{ secrets.BROCOLI_DOCKER_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: brocolidata/dataplatform_lab

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}