name: Push Docker Image

on:
  workflow_dispatch:
    
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main
    paths:
    - 'docker/**'

jobs:

  push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.BROCOLI_DOCKER_USERNAME }}
          password: ${{ secrets.BROCOLI_DOCKER_TOKEN }}

      - name: Build image
        run: |
          docker compose \
            -f docker/docker-compose.yml \
          build

      - name: Push image to Docker Hub Container Registry
        run: |
          docker compose \
            -f docker_build/docker-compose.yml \
          push